# Generated by Django 4.2.24 on 2025-09-25 21:38
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    operations = [
        CreateExtension("postgis"),
    ]
